### PR TITLE
Non CE Tab styling

### PR DESCRIPTION
**Pull request by ciar4n**
Implementing... https://magazine.joomla.org/issues/issue-nov-2017/item/3289-episode-iv-a-new-user-interface-for-the-joomla-backend

### Summary of Changes
Initial styling for tabs. 

image

### CODE REVIEW

**Comment by ciar4n** [comment]
@svom @coolcat-creations 

In your design, tab links are justified across the top. This seems a little strange to me if there is a small number of tabs.

Eg.

image

**Comment by svom** [comment]
I see your point. Actually I'm not to sure how to proceed, but i think that these big taps also can work very well because you have these big buttons. Also regarding a11y it can be quite useful because it's easy to point at the right buttons for people with decreased motoric abilities.

**Comment by coolcat-creations** [comment]
grafik

**Comment by coolcat-creations** [comment]
Yes, I can do that... But its 261 designed pages because every possible state is in there. I will send you the full pdf for now and post the designs this week :)

**Comment by ciar4n** [comment]
All I really need is...

- Each view type (dashboard, list and edit). 
- com_admin and com_cpanel
- Each UI element including various states if applicable (eg. dropdown open)

**Comment by ciar4n** [comment]
On that last point it is best to have a single style for each UI element. In your design the styling for select fields for example appear to vary depending on the page it is displayed on. Creating a custom element for each variation depending on the page it is displayed on is probably something we want to avoid (@dgrammatiko ?) .

**Comment by dgrammatiko** [comment]
couple observations:
- the tabs at the bottom break any kind of accessibility because the navigation needs to be before the content (unless we use css grid layout I don't see this as feasible for J4)
- again for accessibility the content needs to be confined in a visible box

An example of a proper accessible tabs component is available here: https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/tabs/tabs-1/tabs.html

Creating a customised component (CE) won't be a huge problem but we're adding a lot more code that we will have to maintain, so I'll support @ciar4n here for a common/unified approach

**Comment by coolcat-creations** [comment]
We agreed on that layout before ;) and it's great for mobile too - so why not using css grid? But lets discuss after I create the single PRs for each section...

**Comment by ciar4n** [comment]
I'd be against placing the tab navigation at the bottom.. 

- Goes against standard expectation for tabs,
- The a11y issues mentioned above
- Having to scroll through content before been able to navigate away from that content (navigation will not always be displayed neatly at the bottom of the viewport).
- I'd question the mobile benefits when you consider the previous comment. Having said that they can be easily switched to the bottom on mobile if it comes to that.

**Comment by coolcat-creations** [comment]
I'm sorry to hear that since we discussed it earlier and agreed on that approach.

for 1) ok
2) would not be an issue if solved with css grid
3) The tabs would be at the bottom just as the bottom bar in the current joomla series 
4) We also discussed the mobile view before...

As stated above I will create PRs for each View so we can continue discussing there further and discuss alternate solutions so that everyone will be happy 😎😎😎

**Comment by ciar4n** [comment]
> I'm sorry to hear that since we discussed it earlier and agreed on that approach.

I can't imagine been in agreement with this but I was largely unavailable at the time the designs were created. I think it is also hard to imagine some of these issues until we go to actually implement them so good to have you here while we do so 😄 

> 2) would not be an issue if solved with css grid

Yes the markup can and will be accessible and also be independent from design using flex or grid however visually I still think there is issues here. A zoomed in screen with keyboard only, if tabs have a large amount of content, tabbing through the navigation a user will only see the end of the tab content.  Also tabbing to the tabs would scroll to the end of the page.

Having said that I am no a11y expert so my comments are based on nothing 😄 . In truth I just feel placing tab navigation at the bottom is more hassle than it is worth.

**Pull request merged**
