### PR TITLE
Fix alert z-index

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #370 .

### Summary of Changes
Alert z-index to low. This PR increases

### Testing Instructions
Save article. Ensure alert appears.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
I think 1041 is ok here

**Comment by brianteeman** [comment]
Replicated the issue and can confirm this PR fixes it

**Comment by brianteeman** [comment]
Correction - it fixes the issue with the alerts in com_content but it breaks the modals in com_finder eg when you press index. see screenshot
chrome_2018-04-17_23-33-53

**Comment by brianteeman** [comment]
actually looks like it is a problem with all modals
chrome_2018-04-17_23-37-04

**Comment by ciar4n** [comment]
@brianteeman Thank you. I believe this issue was present before this PR (https://github.com/joomla/joomla-cms/issues/19408).

The issue (as I see it) is the modal markup follows directly after the element that triggers it (eg. index button). So if a triggers container has a z-index, the modal will inherit it. Hence why this issue depends on where the modal was triggered.

**Comment by ciar4n** [comment]
> I think 1041 is ok here

I try to keep within the bootstrap scale of 1000 - 1100 in units of 10 for lightboxes/modals.

**Comment by brianteeman** [comment]
ok

**Comment by dgrammatiko** [comment]
> I try to keep within the bootstrap scale of 1000 - 1100

Isn't that thing customisable in the _viariables.scss ?
I mean is there a reason to keep these hideous values?

**Comment by ciar4n** [comment]
> I mean is there a reason to keep these hideous values?

There is some logic to them when dealing with lightboxes/modals as they should be above everything else. I'm happy changing it if you feel strongly against them.

**Comment by ciar4n** [comment]
@dgrammatiko Is it possible to move the modal markup to just inside the closing body tag to resolve the issue indicated by @brianteeman ? Maybe you know of another solution?

**Comment by ciar4n** [comment]
Don't do anything yet. Probably an easier way around it. I'll have a closer look later.

**Comment by ciar4n** [comment]
I have reshuffled the z-index so the modal works in most cases. There is one instance that I can't get around and that is when the modal is triggered from the toolbar. This issue is also present in Joomla 3 although not as obvious. Issue create.. https://github.com/joomla/joomla-cms/issues/20255

**Pull request merged**
