### PR TITLE
UI-tabs as CE

### PR DESCRIPTION
**Pull request by dgt41**
Pull Request for Issue # .
As requested yesterday

### Summary of Changes
Affects only:
- Article edit
- category edit
- Layout params
- field Rules (permissions)

### NOTES
- The tabs are not synced with the other repo (custom elements)
- Reason is to allow you to compile the scss you need easier (node build.js --compilecescss)
- files at /build/webcomponents/tab (js and scss)
Please ignore any possible bugs related to js, this is **not** the final code

### Preview
Normal (tabs) view
screen shot 2018-03-02 at 09 39 03

narrow (collapsed to accordion) view
screen shot 2018-03-02 at 09 39 33

### CODE REVIEW

**Comment by ciar4n** [comment]
We must remember to convert the web component SCSS to actual SCSS at some point

**Comment by C-Lodder** [comment]
@ciar4n true true. We can do that in the actual CE repo and get Dimitris to bump the version. I believe we did it for a couple of elements in toiletkit (including proper variables) so I can port the base SCSS over to the new repo for us to change the styling.

**Comment by dgt41** [comment]
> Only issue is IE11 is throwing an error regarding Object in webcomponents-ce.js

Is this repo in sync with the main repo? There shouldn't be a webcomponents-ce.js anymore

**Comment by C-Lodder** [comment]
@dgt41 was last synced 10 days ago. I'll resync today

**Pull request merged**
