### PR TITLE
Start styling for header and dashboard

### PR DESCRIPTION
**Pull request by C-Lodder**
@ciar4n 

screeny

### CODE REVIEW

**Comment by brianteeman** [comment]
the background-colour for badge-secondary of 868e96 fails accessibility try with #6F7780 instead?

**Comment by brianteeman** [comment]
The hover on the quickicons is so subtle I didnt see it

```
.quick-icons a:hover, .quick-icons a:hover, .quick-icons a:focus {
    text-decoration: none;
    box-shadow: 0 0 5px 0 rgba(0,0,0,0.3);
}
```

Not a designer myself (obviously) but perhaps 10px for the shadow would be better

**Comment by C-Lodder** [comment]
@brianteeman done

@ciar4n sidebar fixed

**Comment by ciar4n** [comment]
@brianteeman I guess so.. issue created.. https://github.com/joomla/40-backend-template/issues/350

**Pull request merged**
