### PR TITLE
Initial table styling - com_content

### PR DESCRIPTION
**Pull request by ciar4n**
Implementing... https://magazine.joomla.org/issues/issue-nov-2017/item/3289-episode-iv-a-new-user-interface-for-the-joomla-backend

### Summary of Changes
Initial styling for tables. Only fully applies to com_content. Need to make sure we are ok removing the component sidebar before applying to others.

image

### CODE REVIEW

**Comment by ciar4n** [comment]
The design has the toolbar button, search and filter inline. We need to obviously reduces the buttons somehow before this is possible.

**Comment by brianteeman** [comment]
Do you think we should have a gap between the search and clear buttons?

chrome_2018-02-22_17-18-44

**Comment by brianteeman** [comment]
>  We need to obviously reduces the buttons somehow before this is possible.

I still believe that progressive disclosure is the only possible fix for that

**Comment by C-Lodder** [comment]
Just a note that because the buttons in the design are flat we'll need to add a separator between grouped buttons, such as the search/clear

**Comment by svom** [comment]
We definitely need a seperator here, but what i ask myself is the question if we need a "clear" button, or if an small x in the input field wouldn't be clear enough. We would also save some space. Not sure if it's possible regarding accessibility, but it could be an approach.

**Comment by brianteeman** [comment]
(are these PR supposed to be mobile as well or is that later?)

**Comment by ciar4n** [comment]
@brianteeman I was gonna leave that till later. Just a little to much to consider at once as it would involve the general layout (sidebar and header).

**Comment by brianteeman** [comment]
@ciar4n just wanted to check if I should be testing that or not?

**Comment by brianteeman** [comment]
There is some confusion on the Clear button
If you look at J3 you will see that the main role of the Clear button is NOT to empty the search but to reset the Search tools. So as J4 has the search tools in the Table Options dropdown I would either group the Clear with that button and not the search OR move the clear inside of the dropdown

**Comment by ciar4n** [comment]
> @ciar4n just wanted to check if I should be testing that or not?

You can ignore mobile for this PR

**Comment by svom** [comment]
bildschirmfoto 2018-02-22 um 18 41 28

@brianteeman You're right. But as you can see, the design-approach was to have a filter dropdown and a dropdown for the list options (which columns should be visible in the overview because most of them are more or less never used). So i would group the clear button with the filter dropdown but not inside and only show it when filters are active. Otherwise it wouldn't make any sense at all to display it.

**Comment by brianteeman** [comment]
Is this the correct image thata this is supposed to be creating?
https://magazine.joomla.org/media/k2/galleries/3289/Content%20-%20Manage%20Articles.png

If so then the article alias needs to be moved to a column and not inline with the article title

**Comment by brianteeman** [comment]
And we appear to have lost the Category column

**Comment by svom** [comment]
@brianteeman 

Article Alias can be moved the a new column and doesnt have to be inline, i guess that's already planed in the drafts you're referring to, it's just the column heading, that is missing. Actually it's the same with the category-column.

**Comment by ciar4n** [comment]
Removing category was me messing up... reverted.

Also separated the clear button...

image

**Comment by ciar4n** [comment]
> Is this the correct image thata this is supposed to be creating?
https://magazine.joomla.org/media/k2/galleries/3289/Content%20-%20Manage%20Articles.png

There seems to be a difference between the design I am working from and this screenshot. I am currently working from the following where neither the alias or category has it's own column...

image

**Comment by ciar4n** [comment]
Moved alias and category to columns..

image

**Comment by brianteeman** [comment]
Category and alias now all good

**Comment by brianteeman** [comment]
Small error with the sort - look at the sort indicators  in this movie

sort

**Comment by brianteeman** [comment]
And as you can see from the movie the sidebar pops out and in when you sort - shouldnt it stay closed?

**Comment by ciar4n** [comment]
> Small error with the sort - look at the sort indicators in this movie

@dgt41 Maybe you could have a look at this. Alias is now working fine but an issue with category sorting. I'm obviously missing something.

**Comment by ciar4n** [comment]
> And as you can see from the movie the sidebar pops out and in when you sort - shouldnt it stay closed?

I think we can ignore this until we re style the sidebar

**Comment by C-Lodder** [comment]
Will take a look when I get home later

**Comment by ciar4n** [comment]
To keep things moving along feel free to merge this. We can create an issue for the sorting.

**Pull request merged**
