### PR TITLE
CSS only sticky toolbar

### PR DESCRIPTION
**Pull request by ciar4n**
A no javascript solution for the sticky toolbar...

fa0d120dfde7724ee7b2eded4fd36b5a

### CODE REVIEW

**Comment by brianteeman** [comment]
ie11?
https://caniuse.com/#search=sticky

**Comment by ciar4n** [comment]
This is not supported by IE11 however the toolbar will remain functional, just will not stick on scroll.

**Comment by dgt41** [comment]
@ciar4n is there any reason that we're still using px instead of rem here?

**Comment by ciar4n** [comment]
@dgt41 The vertical padding? Personally I like to leave 'layout' values in px as you don't want them increasing if the base font size is increased. You believe otherwise?

**Pull request merged**
